logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  cloud:
    gateway:
      routes:
        - id: github_route
          uri: https://github.com
          predicates:
          - Path=/api/**
          filters:
          - StripPrefix=1

server:
  port: 9000